### ISSUE TITLE
Error when setting token

### ISSUE THREAD

**Issue by michbsd** [moranje/alfred-workflow-todoist#42]
Hi,

I am unable to set the token. When running the command manually, I get : 

```
node alfred-workflow-todoist.js settings:store {"key":"token","value":"XX2ca926568d6XXXXXXXXXXXXXXXX4d10aXX"}                      
undefined:1
key:token value:XX2ca926568d6XXXXXXXXXXXXXXXX4d10aXX
^

SyntaxError: Unexpected token k in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/mich/Dropbox/AlfredSync/Alfred.alfredpreferences/workflows/user.workflow.FFA6C1E7-2D50-40E4-BF0B-E517D78738EF/alfred-workflow-todoist.js:55008:39)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
```

node: v10.1.0
OS: mojave
Workflow: 5.4.3
Alfred: 3.7

**Comment by moranje** [comment]
Try 5.4.5 and let me know if you still run into problems. If you do an error log from the alfred debug screen helps

**Comment by michbsd** [comment]
Still not working. 

From alfred debug:

[2018-10-10 13:56:09][utility.debug] 'Something went wrong

Error: ENOENT: no such file or directory, open '/Users/mich/Library/Application Support/Alfred 3/Workflow Data/com.alfred-workflow-todoist/settings.json'

ALFRED WORKFLOW TODOIST
----------------------------------------
os: macOS
query: {"key":"token","value":"<token>"}
node.js: v10.1.0
alfred: 3.7
workflow: 5.4.5
Stack: Error: ENOENT: no such file or directory, open '/Users/mich/Library/Application Support/Alfred 3/Workflow Data/com.alfred-workflow-todoist/settings.json'
', {}

**Comment by michbsd** [comment]
OK - I got it working, by manually creating : 
~/Library/Application Support/Alfred 3/Workflow Data/com.alfred-workflow-todoist/settings.json

and also,

~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.alfred-workflow-todoist/cache.json

**Comment by moranje** [comment]
Hmmm maybe a permission thing, not sure why it won't create these files. Do you happen to know?

**Comment by robcapell** [comment]
Having this issue as well - "No such file or directory". I manually created the folder and two files as @michbsd recommends, but I'm still receiving the same error.  node -v 8.4.0, OSX 10.14, Alfred 3

**Comment by michbsd** [comment]
@moranje I had to create the folders.

**Comment by technovangelist** [comment]
Just installed this workflow. Like the others, I created ~/Library/Application Support/Alfred 3/Workflow Data/com.alfred-workflow-todoist then ran touch settings.json. then created ~/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.alfred-workflow-todoist and ran touch cache.json

Now everything works

**Comment by moranje** [comment]
Alright thanks for drilling this down, expect a fix soon

---
Martien

________________________________

**Comment by moranje** [comment]
This should be fixed in `5.5.0`

**Comment by jottr** [comment]
Issue remains. Creating the relevant folders as suggested [here](https://github.com/moranje/alfred-workflow-todoist/issues/42#issuecomment-428545394) didn't fix it.

**Comment by moranje** [comment]
> Issue remains. Creating the relevant folders as suggested [here](https://github.com/moranje/alfred-workflow-todoist/issues/42#issuecomment-428545394) didn't fix it.

I need a little more than this. Any debug logs or error information?

Also michbsd created the files as well in the comment you linked to, let me know if that fixes your problem.
